# Getting and Knowing Data (pandas)

In [ ]:
import pandas as pd
import numpy as np

Step 1: Import Dataset

In [ ]:
df = pd.read_csv("chipotle.tsv", sep='\t')
print (df.head(10))

Step 2: Dataset overview

In [ ]:
print (df.shape)

In [ ]:
print (df.info())

In [ ]:
print (list(df.columns))

In [ ]:
df.index

In [ ]:
df.describe()

In [ ]:
df.loc[df.item_name == 'Chicken Salad Bowl']

In [ ]:
print ('Anh Khôi đẹp trai nhửt thế gian')

In [ ]:
a = [x for x in range (10)]
print (a)

# Numpy

In [50]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
[1.2, 3,4,5]

In [ ]:
np.array([1.2, 3,4,5])

In [ ]:
np.array([1,2,3,4,], dtype = 'float64')

In [61]:
a2 = np.array([[1,2,3],[4,5,6]], dtype = 'int64')

In [62]:
a2.dtype

dtype('int64')

In [60]:
a2.size

6

In [63]:
a2.shape

(2, 3)

Creating Numpy Arrays from Scratch

In [ ]:
np.zeros([2,5], dtype = int )


In [ ]:
np.ones([3,3], dtype = float)

In [ ]:
np.arange(2,20,2,dtype = int)

In [ ]:
np.full((4,6), 3.5 )

In [ ]:
np.linspace(2, 10, 5, dtype=int)

In [ ]:
np.__version__

random

In [ ]:
np.random.random(size = (1))

In [ ]:
np.random.normal(5,2,size=(2,2))

In [ ]:
np.random.randint(-5, 5, size = (4,3))

In [ ]:
np.random.rand(4,4)

Array index & slicing

One - dimentional subarray

In [ ]:
x1 = np.random.randint(20, size = 6)

In [ ]:
x1

In [ ]:
x1[4], x1[0], x1[-1]

mutil-dimensional array

In [ ]:
x2 = np.random.randint(10, size = (4,5))

In [ ]:
x2

In [ ]:
x2[2,4]

In [ ]:
x2[0,2] = 6

In [ ]:
x2

slicing 
x[start, end, step]


In [39]:
x1

array([ 1,  8, 11,  0, 19, 13])

In [40]:
x1[::2]

array([ 1, 11, 19])

In [42]:
x2

array([[3, 5, 6, 0, 3],
       [4, 6, 9, 2, 1],
       [7, 8, 0, 1, 8],
       [3, 5, 9, 5, 0]])

In [47]:
# two rows, three columns
x2[1:3, 1:4]

array([[6, 9, 2],
       [8, 0, 1]])

Reshaping of arrays & transpose

In [53]:
grid = np.arange(1,10)
grid.shape


(9,)

In [55]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
x = np.array([1,2,3])

In [57]:
x.shape

(3,)

In [59]:
x.reshape(1,3).shape

(1, 3)

In [64]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [66]:
x = np.array([[1,2],
              [3,4]])

In [68]:
x.T

array([[1, 3],
       [2, 4]])

array concatenation and splitting

In [69]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [76]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [81]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
np.concatenate((grid, grid), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [85]:
# vstack
x = np.array([1,2,3])

grid = np.array([[1,2,3],
                 [4,5,6]])

In [91]:
np.vstack((x, grid))

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [93]:
x = np.array([[1],
              [2]])
y = np.array([[3],
              [4]])
np.hstack((x, y))

array([[1, 3],
       [2, 4]])